# When working on Eden in Nuclide, it is helpful to scope
# the project to the following directories:
paths = [
  # Note that the order of this list is the order these folders will be
  # displayed in Nuclide's file tree, so we list "eden" and "folly" at the top
  # because those are the directories an Eden developer is the most likely
  # to need to look in.
  #
  # In particular, the first folder is declared the "current working root"
  # in Nuclide, so it is particularly important that "eden" is listed first.
  ".",
  "../folly",
  "../scm",
  "../watchman",
  "../common",
]
