_cc() {
    local i cur prev opts cmd
    COMPREPLY=()
    if [[ "${BASH_VERSINFO[0]}" -ge 4 ]]; then
        cur="$2"
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
    fi
    prev="$3"
    cmd=""
    opts=""

    for i in "${COMP_WORDS[@]:0:COMP_CWORD}"
    do
        case "${cmd},${i}" in
            ",$1")
                cmd="cc"
                ;;
            cc,autoland)
                cmd="cc__autoland"
                ;;
            cc,completions)
                cmd="cc__completions"
                ;;
            cc,config)
                cmd="cc__config"
                ;;
            cc,doctor)
                cmd="cc__doctor"
                ;;
            cc,entry)
                cmd="cc__entry"
                ;;
            cc,help)
                cmd="cc__help"
                ;;
            cc,hooks)
                cmd="cc__hooks"
                ;;
            cc,init)
                cmd="cc__init"
                ;;
            cc,land)
                cmd="cc__land"
                ;;
            cc,pop)
                cmd="cc__pop"
                ;;
            cc,push)
                cmd="cc__push"
                ;;
            cc,rebase)
                cmd="cc__rebase"
                ;;
            cc,setup)
                cmd="cc__setup"
                ;;
            cc,show)
                cmd="cc__show"
                ;;
            cc,stack)
                cmd="cc__stack"
                ;;
            cc,status)
                cmd="cc__status"
                ;;
            cc,sync)
                cmd="cc__sync"
                ;;
            cc,tui)
                cmd="cc__tui"
                ;;
            cc,version)
                cmd="cc__version"
                ;;
            cc,viz)
                cmd="cc__viz"
                ;;
            cc__completions,generate)
                cmd="cc__completions__generate"
                ;;
            cc__completions,help)
                cmd="cc__completions__help"
                ;;
            cc__completions,install)
                cmd="cc__completions__install"
                ;;
            cc__completions,status)
                cmd="cc__completions__status"
                ;;
            cc__completions__help,generate)
                cmd="cc__completions__help__generate"
                ;;
            cc__completions__help,help)
                cmd="cc__completions__help__help"
                ;;
            cc__completions__help,install)
                cmd="cc__completions__help__install"
                ;;
            cc__completions__help,status)
                cmd="cc__completions__help__status"
                ;;
            cc__config,get)
                cmd="cc__config__get"
                ;;
            cc__config,help)
                cmd="cc__config__help"
                ;;
            cc__config,list)
                cmd="cc__config__list"
                ;;
            cc__config,set)
                cmd="cc__config__set"
                ;;
            cc__config,unset)
                cmd="cc__config__unset"
                ;;
            cc__config__help,get)
                cmd="cc__config__help__get"
                ;;
            cc__config__help,help)
                cmd="cc__config__help__help"
                ;;
            cc__config__help,list)
                cmd="cc__config__help__list"
                ;;
            cc__config__help,set)
                cmd="cc__config__help__set"
                ;;
            cc__config__help,unset)
                cmd="cc__config__help__unset"
                ;;
            cc__entry,checkout)
                cmd="cc__entry__checkout"
                ;;
            cc__entry,help)
                cmd="cc__entry__help"
                ;;
            cc__entry,list)
                cmd="cc__entry__list"
                ;;
            cc__entry,status)
                cmd="cc__entry__status"
                ;;
            cc__entry__help,checkout)
                cmd="cc__entry__help__checkout"
                ;;
            cc__entry__help,help)
                cmd="cc__entry__help__help"
                ;;
            cc__entry__help,list)
                cmd="cc__entry__help__list"
                ;;
            cc__entry__help,status)
                cmd="cc__entry__help__status"
                ;;
            cc__help,autoland)
                cmd="cc__help__autoland"
                ;;
            cc__help,completions)
                cmd="cc__help__completions"
                ;;
            cc__help,config)
                cmd="cc__help__config"
                ;;
            cc__help,doctor)
                cmd="cc__help__doctor"
                ;;
            cc__help,entry)
                cmd="cc__help__entry"
                ;;
            cc__help,help)
                cmd="cc__help__help"
                ;;
            cc__help,hooks)
                cmd="cc__help__hooks"
                ;;
            cc__help,init)
                cmd="cc__help__init"
                ;;
            cc__help,land)
                cmd="cc__help__land"
                ;;
            cc__help,pop)
                cmd="cc__help__pop"
                ;;
            cc__help,push)
                cmd="cc__help__push"
                ;;
            cc__help,rebase)
                cmd="cc__help__rebase"
                ;;
            cc__help,setup)
                cmd="cc__help__setup"
                ;;
            cc__help,show)
                cmd="cc__help__show"
                ;;
            cc__help,stack)
                cmd="cc__help__stack"
                ;;
            cc__help,status)
                cmd="cc__help__status"
                ;;
            cc__help,sync)
                cmd="cc__help__sync"
                ;;
            cc__help,tui)
                cmd="cc__help__tui"
                ;;
            cc__help,version)
                cmd="cc__help__version"
                ;;
            cc__help,viz)
                cmd="cc__help__viz"
                ;;
            cc__help__completions,generate)
                cmd="cc__help__completions__generate"
                ;;
            cc__help__completions,install)
                cmd="cc__help__completions__install"
                ;;
            cc__help__completions,status)
                cmd="cc__help__completions__status"
                ;;
            cc__help__config,get)
                cmd="cc__help__config__get"
                ;;
            cc__help__config,list)
                cmd="cc__help__config__list"
                ;;
            cc__help__config,set)
                cmd="cc__help__config__set"
                ;;
            cc__help__config,unset)
                cmd="cc__help__config__unset"
                ;;
            cc__help__entry,checkout)
                cmd="cc__help__entry__checkout"
                ;;
            cc__help__entry,list)
                cmd="cc__help__entry__list"
                ;;
            cc__help__entry,status)
                cmd="cc__help__entry__status"
                ;;
            cc__help__hooks,add)
                cmd="cc__help__hooks__add"
                ;;
            cc__help__hooks,install)
                cmd="cc__help__hooks__install"
                ;;
            cc__help__hooks,remove)
                cmd="cc__help__hooks__remove"
                ;;
            cc__help__hooks,status)
                cmd="cc__help__hooks__status"
                ;;
            cc__help__hooks,uninstall)
                cmd="cc__help__hooks__uninstall"
                ;;
            cc__help__stack,abort-land)
                cmd="cc__help__stack__abort__land"
                ;;
            cc__help__stack,abort-rebase)
                cmd="cc__help__stack__abort__rebase"
                ;;
            cc__help__stack,auto-land)
                cmd="cc__help__stack__auto__land"
                ;;
            cc__help__stack,check)
                cmd="cc__help__stack__check"
                ;;
            cc__help__stack,continue-land)
                cmd="cc__help__stack__continue__land"
                ;;
            cc__help__stack,continue-rebase)
                cmd="cc__help__stack__continue__rebase"
                ;;
            cc__help__stack,create)
                cmd="cc__help__stack__create"
                ;;
            cc__help__stack,delete)
                cmd="cc__help__stack__delete"
                ;;
            cc__help__stack,land)
                cmd="cc__help__stack__land"
                ;;
            cc__help__stack,land-status)
                cmd="cc__help__stack__land__status"
                ;;
            cc__help__stack,list)
                cmd="cc__help__stack__list"
                ;;
            cc__help__stack,list-prs)
                cmd="cc__help__stack__list__prs"
                ;;
            cc__help__stack,pop)
                cmd="cc__help__stack__pop"
                ;;
            cc__help__stack,prs)
                cmd="cc__help__stack__prs"
                ;;
            cc__help__stack,push)
                cmd="cc__help__stack__push"
                ;;
            cc__help__stack,rebase)
                cmd="cc__help__stack__rebase"
                ;;
            cc__help__stack,rebase-status)
                cmd="cc__help__stack__rebase__status"
                ;;
            cc__help__stack,show)
                cmd="cc__help__stack__show"
                ;;
            cc__help__stack,status)
                cmd="cc__help__stack__status"
                ;;
            cc__help__stack,submit)
                cmd="cc__help__stack__submit"
                ;;
            cc__help__stack,switch)
                cmd="cc__help__stack__switch"
                ;;
            cc__help__stack,sync)
                cmd="cc__help__stack__sync"
                ;;
            cc__help__stack,validate)
                cmd="cc__help__stack__validate"
                ;;
            cc__help__viz,deps)
                cmd="cc__help__viz__deps"
                ;;
            cc__help__viz,stack)
                cmd="cc__help__viz__stack"
                ;;
            cc__hooks,add)
                cmd="cc__hooks__add"
                ;;
            cc__hooks,help)
                cmd="cc__hooks__help"
                ;;
            cc__hooks,install)
                cmd="cc__hooks__install"
                ;;
            cc__hooks,remove)
                cmd="cc__hooks__remove"
                ;;
            cc__hooks,status)
                cmd="cc__hooks__status"
                ;;
            cc__hooks,uninstall)
                cmd="cc__hooks__uninstall"
                ;;
            cc__hooks__help,add)
                cmd="cc__hooks__help__add"
                ;;
            cc__hooks__help,help)
                cmd="cc__hooks__help__help"
                ;;
            cc__hooks__help,install)
                cmd="cc__hooks__help__install"
                ;;
            cc__hooks__help,remove)
                cmd="cc__hooks__help__remove"
                ;;
            cc__hooks__help,status)
                cmd="cc__hooks__help__status"
                ;;
            cc__hooks__help,uninstall)
                cmd="cc__hooks__help__uninstall"
                ;;
            cc__stack,abort-land)
                cmd="cc__stack__abort__land"
                ;;
            cc__stack,abort-rebase)
                cmd="cc__stack__abort__rebase"
                ;;
            cc__stack,auto-land)
                cmd="cc__stack__auto__land"
                ;;
            cc__stack,check)
                cmd="cc__stack__check"
                ;;
            cc__stack,continue-land)
                cmd="cc__stack__continue__land"
                ;;
            cc__stack,continue-rebase)
                cmd="cc__stack__continue__rebase"
                ;;
            cc__stack,create)
                cmd="cc__stack__create"
                ;;
            cc__stack,delete)
                cmd="cc__stack__delete"
                ;;
            cc__stack,help)
                cmd="cc__stack__help"
                ;;
            cc__stack,land)
                cmd="cc__stack__land"
                ;;
            cc__stack,land-status)
                cmd="cc__stack__land__status"
                ;;
            cc__stack,list)
                cmd="cc__stack__list"
                ;;
            cc__stack,list-prs)
                cmd="cc__stack__list__prs"
                ;;
            cc__stack,pop)
                cmd="cc__stack__pop"
                ;;
            cc__stack,prs)
                cmd="cc__stack__prs"
                ;;
            cc__stack,push)
                cmd="cc__stack__push"
                ;;
            cc__stack,rebase)
                cmd="cc__stack__rebase"
                ;;
            cc__stack,rebase-status)
                cmd="cc__stack__rebase__status"
                ;;
            cc__stack,show)
                cmd="cc__stack__show"
                ;;
            cc__stack,status)
                cmd="cc__stack__status"
                ;;
            cc__stack,submit)
                cmd="cc__stack__submit"
                ;;
            cc__stack,switch)
                cmd="cc__stack__switch"
                ;;
            cc__stack,sync)
                cmd="cc__stack__sync"
                ;;
            cc__stack,validate)
                cmd="cc__stack__validate"
                ;;
            cc__stack__help,abort-land)
                cmd="cc__stack__help__abort__land"
                ;;
            cc__stack__help,abort-rebase)
                cmd="cc__stack__help__abort__rebase"
                ;;
            cc__stack__help,auto-land)
                cmd="cc__stack__help__auto__land"
                ;;
            cc__stack__help,check)
                cmd="cc__stack__help__check"
                ;;
            cc__stack__help,continue-land)
                cmd="cc__stack__help__continue__land"
                ;;
            cc__stack__help,continue-rebase)
                cmd="cc__stack__help__continue__rebase"
                ;;
            cc__stack__help,create)
                cmd="cc__stack__help__create"
                ;;
            cc__stack__help,delete)
                cmd="cc__stack__help__delete"
                ;;
            cc__stack__help,help)
                cmd="cc__stack__help__help"
                ;;
            cc__stack__help,land)
                cmd="cc__stack__help__land"
                ;;
            cc__stack__help,land__status)
                cmd="cc__stack__help__land__status"
                ;;
            cc__stack__help,list)
                cmd="cc__stack__help__list"
                ;;
            cc__stack__help,list__prs)
                cmd="cc__stack__help__list__prs"
                ;;
            cc__stack__help,pop)
                cmd="cc__stack__help__pop"
                ;;
            cc__stack__help,prs)
                cmd="cc__stack__help__prs"
                ;;
            cc__stack__help,push)
                cmd="cc__stack__help__push"
                ;;
            cc__stack__help,rebase)
                cmd="cc__stack__help__rebase"
                ;;
            cc__stack__help,rebase__status)
                cmd="cc__stack__help__rebase__status"
                ;;
            cc__stack__help,show)
                cmd="cc__stack__help__show"
                ;;
            cc__stack__help,status)
                cmd="cc__stack__help__status"
                ;;
            cc__stack__help,submit)
                cmd="cc__stack__help__submit"
                ;;
            cc__stack__help,switch)
                cmd="cc__stack__help__switch"
                ;;
            cc__stack__help,sync)
                cmd="cc__stack__help__sync"
                ;;
            cc__stack__help,validate)
                cmd="cc__stack__help__validate"
                ;;
            cc__stack__land)
                cmd="cc__stack__land"
                ;;
            cc__stack__land__status)
                cmd="cc__stack__land__status"
                ;;
            cc__stack__list)
                cmd="cc__stack__list"
                ;;
            cc__stack__list__prs)
                cmd="cc__stack__list__prs"
                ;;
            cc__stack__pop)
                cmd="cc__stack__pop"
                ;;
            cc__stack__prs)
                cmd="cc__stack__prs"
                ;;
            cc__stack__push)
                cmd="cc__stack__push"
                ;;
            cc__stack__rebase)
                cmd="cc__stack__rebase"
                ;;
            cc__stack__rebase__status)
                cmd="cc__stack__rebase__status"
                ;;
            cc__stack__show)
                cmd="cc__stack__show"
                ;;
            cc__stack__status)
                cmd="cc__stack__status"
                ;;
            cc__stack__submit)
                cmd="cc__stack__submit"
                ;;
            cc__stack__switch)
                cmd="cc__stack__switch"
                ;;
            cc__stack__sync)
                cmd="cc__stack__sync"
                ;;
            cc__stack__validate)
                cmd="cc__stack__validate"
                ;;
            cc__status)
                cmd="cc__status"
                ;;
            cc__sync)
                cmd="cc__sync"
                ;;
            cc__tui)
                cmd="cc__tui"
                ;;
            cc__version)
                cmd="cc__version"
                ;;
            cc__viz)
                cmd="cc__viz"
                ;;
            cc__viz__deps)
                cmd="cc__viz__deps"
                ;;
            cc__viz__help)
                cmd="cc__viz__help"
                ;;
            cc__viz__help__deps)
                cmd="cc__viz__help__deps"
                ;;
            cc__viz__help__help)
                cmd="cc__viz__help__help"
                ;;
            cc__viz__help__stack)
                cmd="cc__viz__help__stack"
                ;;
            cc__viz__stack)
                cmd="cc__viz__stack"
                ;;
    esac
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    complete -F _cc -o nosort -o bashdefault -o default cc
else
    complete -F _cc -o bashdefault -o default cc
fi
