name: cascade-cli
base: core22
version: '0.1.0'
summary: Stacked diffs CLI for Bitbucket Server
description: |
  Cascade CLI is a powerful command-line tool for managing stacked diffs in Git 
  repositories with Bitbucket Server integration.
  
  Features:
  - Stacked Diff Workflow - Chain related commits for better code review
  - Smart Conflict Resolution - Auto-resolves 60-80% of common rebase conflicts
  - Smart Force Push - Preserves review history during rebases
  - Bitbucket Integration - Seamless PR management
  - Terminal UI - Interactive stack browser and management
  - Visualizations - ASCII, Mermaid, Graphviz, PlantUML formats
  - Git Hooks - Automated workflow enforcement
  - Shell Completions - Bash, Zsh, Fish, PowerShell support

grade: stable
confinement: classic

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  cascade-cli:
    command: bin/cc
    aliases: [cc]

parts:
  cascade-cli:
    plugin: rust
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
      - git
    stage-packages:
      - git
      - ca-certificates
    rust-channel: stable
    rust-features: []
    
  completions:
    plugin: dump
    source: completions/
    organize:
      '*': usr/share/bash-completion/completions/ 