name: Update Homebrew Tap

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., v0.1.1)'
        required: false
        type: string

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: JAManfredi/homebrew-cascade-cli
          path: homebrew-tap
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
      
      - name: Update formula version
        run: |
          # Get version from release or input
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          
          # Remove 'v' prefix if present
          VERSION="${VERSION#v}"
          
          echo "Updating formula to version $VERSION"
          
          # Download release assets to calculate checksums
          echo "Downloading release assets..."
          curl -L -o csc-macos-arm64.tar.gz \
            "https://github.com/JAManfredi/cascade-cli/releases/download/v${VERSION}/csc-macos-arm64.tar.gz"
          curl -L -o csc-macos-x64.tar.gz \
            "https://github.com/JAManfredi/cascade-cli/releases/download/v${VERSION}/csc-macos-x64.tar.gz"
          
          # Calculate checksums
          ARM64_SHA=$(shasum -a 256 csc-macos-arm64.tar.gz | cut -d' ' -f1)
          X64_SHA=$(shasum -a 256 csc-macos-x64.tar.gz | cut -d' ' -f1)
          
          echo "ARM64 SHA256: $ARM64_SHA"
          echo "X64 SHA256: $X64_SHA"
          
          # Update the formula
          cd homebrew-tap
          
          # Update version and URLs
          sed -i "s/version \"[^\"]*\"/version \"${VERSION}\"/" Formula/cascade-cli.rb
          sed -i "s|download/v[^/]*/|download/v${VERSION}/|g" Formula/cascade-cli.rb
          
          # Update checksums
          sed -i "/arm64.tar.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${ARM64_SHA}\"/" Formula/cascade-cli.rb
          sed -i "/x64.tar.gz/,/sha256/ s/sha256 \"[^\"]*\"/sha256 \"${X64_SHA}\"/" Formula/cascade-cli.rb
          
      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          VERSION="${{ github.event.release.tag_name || github.event.inputs.version }}"
          git add Formula/cascade-cli.rb
          git commit -m "Update Cascade CLI to ${VERSION}"
          git push
      
      - name: Test formula
        run: |
          # Simple syntax check
          cd homebrew-tap
          ruby -c Formula/cascade-cli.rb